version: '3'
services:
  ma6-main:
    image: 2swo/ma6-menbosha-back
    ports:
      - '3000:3000'
    env_file:
      - .env.development
      # - .env.production (베포 ec2에서의 설정입니다)
    restart: always

  redis:
    image: 2swo/redis
    volumes:
      - redis_data:/usr/local/etc/redis
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    env_file:
      - .env.redis
    ports:
      - '6379:6379'
    restart: always

  api-nginx-certbot:
    image: 2swo/back-nginx-certbot
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .env.nginx-certbot

    # dev-nginx-certbot:
    # image: 2swo/dev-back-nginx-certbot
    # ports:
    #   - '80:80'
    #   - '443:443'
    # env_file:
    #   - .env.nginx-certbot

  # mysql 이미지는 따로 dockerfile로 빌드되진 않습니다.
  # version과 port,env파일명,command 참고하시면 될 것 같습니다.
  # development_db:
  #   image: mysql:8.0.36
  #   restart: unless-stopped
  #   ports:
  #     - '3306:3306'
  #   env_file:
  #     - .env.mysql
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci

volumes:
  redis_data:
