version: '3'
services:
  ma6-main:
    image: 2swo/ma6-menbosha-back
    ports:
      - '3000:3000'
    env_file:
      - .env.development
      # - .env.production (베포 ec2에서의 설정입니다)
    restart: always

  redis:
    image: 2swo/redis
    volumes:
      - redis_data:/usr/local/etc/redis
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    env_file:
      - .redis.env
    ports:
      - '6379:6379'
    restart: always

  nginx-certbot:
    image: 2swo/back-nginx-certbot
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - .nginx-certbot.env

volumes:
  redis_data:
