version: '3'
services:
  ma6-main:
    image: 2swo/ma6-menbosha-back
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always
    environment:
      - TZ=Asia/Seoul

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --port 6379
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
